// Thin barrel: existing import paths stay on server/attachments.ts.
// Policy modules live in server/attachments/.

export {
  CHANNEL_UPLOAD_LIMITS,
  acpImageBlocks,
  agentAcceptsImagePrompts,
  assessRemoteAttachmentUrl,
  attachmentPathRefs,
  attachmentPreviewDecision,
  attachmentPreviewExcerpt,
  channelUploadLimits,
  claudeImageBlocks,
  codexImageInput,
  DEFAULT_INLINE_MAX_BYTES,
  degradeIfOversized,
  detectAttachmentMime,
  detectImageMediaType,
  detectMimeFromBytes,
  detectMimeFromName,
  downloadRemoteAttachment,
  enforceChannelUploadLimits,
  expandAttachmentPaths,
  extractImageDimensions,
  isBlockedLiteralAddress,
  isOversized,
  isSecretConfigPath,
  oversizedMetadataStub,
  readImageBytes,
  safeOpenAttachment,
  summarizeAttachment,
  type AttachmentPreviewDecision,
  type AttachmentPreviewKind,
  type AttachmentSummary,
  type ChannelAttachmentCandidate,
  type ChannelUploadLimits,
  type ChannelUploadResult,
  type CodexImageInput,
  type ImageBytes,
  type ImageDimensions,
  type OversizedAttachmentStub,
  type RemoteDownloadOptions,
  type RemoteDownloadResult,
  type RemoteUrlDecision,
  type RemoteUrlLookup,
  type RemoteUrlPolicyOptions,
  type SafeOpenDecision,
  type SafeOpenMode,
} from "./attachments/index.ts";
