// A2 Avatar Tier B: raster portraits from an image provider. Prompt is a
// pure function of the bot's name + personality. Bytes go through
// blobs.ts (content-addressed files); SQLite holds only hashes. The
// generator is injectable so default `pnpm test` never hits a network.
import { deflateSync } from "node:zlib";

import type { AppConfig } from "./config.ts";
import { HASH_RE, putBlob, validBlobHash } from "./db/blobs.ts";

export const AVATAR_PROVIDERS = ["xai", "openai", "openrouter"] as const;
export type AvatarProvider = (typeof AVATAR_PROVIDERS)[number];

export const AVATAR_CANDIDATE_COUNT = 4;

export interface AvatarPromptInput {
  name?: string;
  title?: string;
  description?: string;
}

export interface AvatarImage {
  bytes: Buffer;
  mime: string;
}

export interface GenerateAvatarImagesInput {
  prompt: string;
  count: number;
  provider: AvatarProvider;
  apiKey: string;
  url?: string;
}

export type GenerateAvatarImages = (input: GenerateAvatarImagesInput) => Promise<AvatarImage[]>;

export interface AvatarCandidate {
  hash: string;
  mime: string;
}

const DEFAULT_URLS: Record<AvatarProvider, string> = {
  xai: "https://api.x.ai/v1",
  openai: "https://api.openai.com/v1",
  openrouter: "https://openrouter.ai/api/v1",
};

const DEFAULT_MODELS: Record<AvatarProvider, string> = {
  xai: "grok-2-image",
  openai: "dall-e-2",
  openrouter: "black-forest-labs/flux-1.1-pro",
};

export function validAvatarProvider(v: unknown): v is AvatarProvider {
  return typeof v === "string" && (AVATAR_PROVIDERS as readonly string[]).includes(v);
}

/** Build the image prompt from the bot's name + personality fields. */
export function avatarPrompt(bot: AvatarPromptInput): string {
  const name = (bot.name ?? "").trim() || "a helpful assistant";
  const personality = [bot.title, bot.description]
    .map((s) => (typeof s === "string" ? s.trim() : ""))
    .filter(Boolean)
    .join(". ");
  const who = `Character portrait avatar of ${name}.`;
  const persona = personality ? ` Personality: ${personality}.` : "";
  return `${who}${persona} Friendly illustrated mascot, head-and-shoulders, centered, simple background, suitable as a small circular app icon.`;
}

export function configuredAvatarProviders(cfg: AppConfig): AvatarProvider[] {
  const out: AvatarProvider[] = [];
  if (cfg.xai?.key) out.push("xai");
  if (cfg.openai?.key) out.push("openai");
  if (cfg.openrouter?.key) out.push("openrouter");
  return out;
}

/** First configured provider, or a requested one when that key is present. */
export function pickAvatarProvider(cfg: AppConfig, requested?: string | null): AvatarProvider | null {
  const available = configuredAvatarProviders(cfg);
  if (!available.length) return null;
  if (requested) {
    if (!validAvatarProvider(requested)) return null;
    return available.includes(requested) ? requested : null;
  }
  return available[0];
}

export function providerKey(cfg: AppConfig, provider: AvatarProvider): string | undefined {
  if (provider === "xai") return cfg.xai?.key;
  if (provider === "openai") return cfg.openai?.key;
  return cfg.openrouter?.key;
}

export function providerUrl(cfg: AppConfig, provider: AvatarProvider): string {
  if (provider === "xai") return cfg.xai?.url || DEFAULT_URLS.xai;
  if (provider === "openai") return cfg.openai?.url || DEFAULT_URLS.openai;
  return cfg.openrouter?.url || DEFAULT_URLS.openrouter;
}

export function collectAvatarHashes(
  bots: ReadonlyArray<{ avatarImageHash?: string | null; avatarCandidates?: string[] }>,
): Set<string> {
  const set = new Set<string>();
  for (const bot of bots) {
    if (validBlobHash(bot.avatarImageHash)) set.add(bot.avatarImageHash);
    for (const hash of bot.avatarCandidates ?? []) {
      if (validBlobHash(hash)) set.add(hash);
    }
  }
  return set;
}

export function validAvatarHashList(v: unknown): string[] | undefined {
  if (!Array.isArray(v)) return undefined;
  const out = v.filter((h): h is string => validBlobHash(h));
  return out.length ? out : undefined;
}

/** Persist generated bytes; returns content hashes. Never writes SQLite. */
export function storeAvatarImages(images: readonly AvatarImage[]): AvatarCandidate[] {
  if (images.length < AVATAR_CANDIDATE_COUNT) {
    throw Object.assign(new Error(`image provider returned ${images.length} image(s); need ${AVATAR_CANDIDATE_COUNT}`), {
      status: 502,
    });
  }
  return images.slice(0, AVATAR_CANDIDATE_COUNT).map((image) => ({
    hash: putBlob(image.bytes),
    mime: image.mime || "image/png",
  }));
}

// ── HTTP image providers (OpenAI-compatible /images/generations) ────────

type FetchFn = typeof fetch;

function noSecrets(text: string, key: string): string {
  if (!key) return text;
  return text.includes(key) ? text.split(key).join("[redacted]") : text;
}

async function readImagesFromResponse(json: unknown, fetchImpl: FetchFn, key: string): Promise<AvatarImage[]> {
  const data = json && typeof json === "object" ? (json as { data?: unknown }).data : undefined;
  if (!Array.isArray(data) || !data.length) throw new Error("image provider returned no images");
  const out: AvatarImage[] = [];
  for (const item of data) {
    if (!item || typeof item !== "object") continue;
    const rec = item as { b64_json?: unknown; url?: unknown };
    if (typeof rec.b64_json === "string" && rec.b64_json) {
      out.push({ bytes: Buffer.from(rec.b64_json, "base64"), mime: "image/png" });
      continue;
    }
    if (typeof rec.url === "string" && rec.url) {
      const res = await fetchImpl(rec.url, { signal: AbortSignal.timeout(30_000) });
      if (!res.ok) throw new Error(noSecrets(`image download failed (HTTP ${res.status})`, key));
      const mime = (res.headers.get("content-type") ?? "image/png").split(";")[0].trim() || "image/png";
      out.push({ bytes: Buffer.from(await res.arrayBuffer()), mime });
    }
  }
  if (!out.length) throw new Error("image provider returned no image bytes");
  return out;
}

export async function generateAvatarImagesHttp(
  input: GenerateAvatarImagesInput,
  fetchImpl: FetchFn = fetch,
): Promise<AvatarImage[]> {
  const { prompt, count, provider, apiKey } = input;
  if (!apiKey) throw Object.assign(new Error("no image provider configured"), { status: 409 });
  const base = (input.url || DEFAULT_URLS[provider]).replace(/\/+$/, "");
  const body = {
    model: DEFAULT_MODELS[provider],
    prompt,
    n: count,
    response_format: "b64_json" as const,
  };
  const headers: Record<string, string> = {
    authorization: `Bearer ${apiKey}`,
    "content-type": "application/json",
  };
  if (provider === "openrouter") {
    headers["http-referer"] = "https://github.com/Velarixx/VelarixBot";
    headers["x-title"] = "VelarixBot";
  }
  const res = await fetchImpl(`${base}/images/generations`, {
    method: "POST",
    headers,
    body: JSON.stringify(body),
    signal: AbortSignal.timeout(60_000),
  });
  if (!res.ok) {
    const text = await res.text().catch(() => "");
    throw Object.assign(new Error(noSecrets(`image provider failed (HTTP ${res.status})${text ? `: ${text.slice(0, 180)}` : ""}`, apiKey)), {
      status: res.status >= 400 && res.status < 500 ? 409 : 502,
    });
  }
  const json = (await res.json()) as unknown;
  const images = await readImagesFromResponse(json, fetchImpl, apiKey);
  if (images.length >= count) return images.slice(0, count);
  // some models (dall-e-3) only return n=1 — fill the rest with parallel calls
  const extra = await Promise.all(
    Array.from({ length: count - images.length }, () =>
      generateAvatarImagesHttp({ ...input, count: 1 }, fetchImpl).then((got) => got[0]),
    ),
  );
  return [...images, ...extra].filter(Boolean).slice(0, count);
}

export async function generateAvatarImagesForConfig(
  cfg: AppConfig,
  input: { prompt: string; requested?: string | null; generate?: GenerateAvatarImages },
): Promise<{ provider: AvatarProvider; candidates: AvatarCandidate[] }> {
  const provider = pickAvatarProvider(cfg, input.requested);
  if (!provider) {
    throw Object.assign(new Error("no image provider configured — add an xAI, OpenAI, or OpenRouter key to generate portraits"), {
      status: 409,
    });
  }
  const apiKey = providerKey(cfg, provider);
  if (!apiKey) {
    throw Object.assign(new Error("no image provider configured"), { status: 409 });
  }
  const generate = input.generate ?? generateAvatarImagesHttp;
  const images = await generate({
    prompt: input.prompt,
    count: AVATAR_CANDIDATE_COUNT,
    provider,
    apiKey,
    url: providerUrl(cfg, provider),
  });
  return { provider, candidates: storeAvatarImages(images) };
}

// ── test fake: four distinct solid PNGs, no network ─────────────────────

function crc32(data: Buffer): number {
  let crc = 0xffffffff;
  for (const byte of data) {
    crc ^= byte;
    for (let i = 0; i < 8; i++) crc = (crc >>> 1) ^ (crc & 1 ? 0xedb88320 : 0);
  }
  return (crc ^ 0xffffffff) >>> 0;
}

function pngChunk(type: string, data: Buffer): Buffer {
  const typeB = Buffer.from(type);
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(Buffer.concat([typeB, data])));
  return Buffer.concat([len, typeB, data, crc]);
}

/** Deterministic solid-color PNG so the fake picker is visible in UI tests. */
export function solidPng(width: number, height: number, rgb: [number, number, number]): Buffer {
  const [r, g, b] = rgb;
  const raw = Buffer.alloc(height * (1 + width * 3));
  for (let y = 0; y < height; y++) {
    const row = y * (1 + width * 3);
    raw[row] = 0;
    for (let x = 0; x < width; x++) {
      const i = row + 1 + x * 3;
      raw[i] = r;
      raw[i + 1] = g;
      raw[i + 2] = b;
    }
  }
  const sig = Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]);
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8;
  ihdr[9] = 2;
  return Buffer.concat([sig, pngChunk("IHDR", ihdr), pngChunk("IDAT", deflateSync(raw)), pngChunk("IEND", Buffer.alloc(0))]);
}

const FAKE_COLORS: Array<[number, number, number]> = [
  [255, 99, 132],
  [54, 162, 235],
  [255, 206, 86],
  [75, 192, 192],
];

/** Four distinct 64×64 PNGs. Used when VELARIX_AVATAR_IMAGE_FAKE=1 or injected. */
export function fakeGenerateAvatarImages(input: GenerateAvatarImagesInput): Promise<AvatarImage[]> {
  const n = input.count > 0 ? input.count : AVATAR_CANDIDATE_COUNT;
  return Promise.resolve(
    Array.from({ length: n }, (_, i) => ({
      bytes: solidPng(64, 64, FAKE_COLORS[i % FAKE_COLORS.length]!),
      mime: "image/png",
    })),
  );
}

export function defaultAvatarImageGenerator(): GenerateAvatarImages {
  if (process.env.VELARIX_AVATAR_LIVE === "1") return generateAvatarImagesHttp;
  if (process.env.VITEST || process.env.VELARIX_AVATAR_IMAGE_FAKE === "1") return fakeGenerateAvatarImages;
  return generateAvatarImagesHttp;
}

export { HASH_RE, validBlobHash };
